FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY data_generator.py .
COPY ip_addresses.csv .

CMD ["python", "-u", "data_generator.py"]

